# Dockerfile for Producer
FROM python
RUN apt-get update
RUN pip install pymongo
RUN pip install multiprocessing
RUN pip install flask
RUN pip install pika
COPY producer.py producer.py
CMD ["python", "producer.py"] 