# Fill in the YAML configuration for the microservices 
#Create a docker-compose file that runs the RabbitMQ server, producer, one database microservice container, and 2 ride-matching containers. The producer’s IP and port must be passed as an environment variable to the ride-matching containers so they can use it to send the request.
version: "2.1"
services:
  rabbitMQ_server:
    image: 
    container_name: 
    ports:
    restart:
  producer:
    image: 
    container_name:
    restart: 
    ports:
    depends_on:
      - rabbitMQ_server
  ride_matching:
    image: 
    container_name: 
    depends_on:
    environment:
      - CONSUMER_ID=
      - PRODUCER_ADDRESS=
  ride_database:
    image: 
    container_name:
    restart:  
    depends_on:
      - producer
  